const fs = require('fs');
const OpenAI = require('openai');

const openai = new OpenAI({
    apiKey: "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"
});

//------------------------------
const agents = require('./agents.js');
const NEWS = require('./news.js');
const { error, info } = require('console');
//------------------------------

class Info {
    constructor(id, content, sender, questions = [], node0Answers=[]) {
        this.infoId = id;
        this.content = content;
        this.sender = sender;
        this.questions = questions; // Questions generated by Node 0 (distributor)
        this.node0Answers = node0Answers;
    }
}

class Node {
    constructor(id, prompt) {
        this.id = id;
        this.prompt = prompt; // The rewriting prompt passed during initialization
        this.neighbors = []; // Store only neighbor IDs
        this.queue = [];
        this.articles = []; // Stores concise data about info received and processed
    }

    // Add neighbor by ID
    addNeighbor(nodeId) {
        this.neighbors.push(nodeId);
    }

    receiveInfo(infoObj) {
        // Ensure questions are received correctly by all nodes
        this.queue.push(infoObj);
    }

    async processInfo() {
        while (this.queue.length > 0) {
            const info = this.queue.shift();
            const updatedInfo = await this.analyzeAndProcess(info); // Ensure all tasks are done here
            this.articles.push(updatedInfo); // Save the updated info in the articles array

            // Distribute the info to neighbors using their IDs
            await this.distribute(updatedInfo, info.sender);
        }
    }

    // Method to analyze, rewrite, answer questions, and calculate misinformation index
    async analyzeAndProcess(info) {
        // Node 0 already generated questions, so we do not generate new ones.
        const rewrittenContent = await rewriteContent(info.content, this.prompt); // Rewrite the content using the node's prompt
        
        if(info.questions.length < 5){
            throw error(`QUESTION LEN LESS THAN 5 ${info.id} ${info.questions}`)
        }

        // Call both answerQuestions in parallel using Promise.all
        const [nodeXAnswers, auditorAnswers] = await Promise.all([
            answerQuestions(info.content, info.questions, this.prompt), // Node X answers
            answerQuestions(info.content, info.questions, `You are an external fact checker that answers yes/no questions based on a given text. Return your response as a JSON object with an 'answers' key containing an array of 1 (for Yes) or 0 (for No).`) // Auditor answers
        ]);

        // Assign auditorAnswers to info object after both API calls are completed
        info.auditorAnswers = auditorAnswers;

        console.log(`NODE INFO ${info} QUESTION LENGTH ${info.questions.length}`)
        console.log(`node0Answers ${info.node0Answers} nodeXAnswers ${nodeXAnswers}, auditorAnswers ${auditorAnswers}`)
        console.log(`node0Answers ${info.node0Answers.length} nodeXAnswers ${nodeXAnswers.length}, auditorAnswers ${auditorAnswers.length}`)
        
        // Calculate the misinformation indices
        const I0 = this.calculateMisinformationIndex(nodeXAnswers, info.node0Answers); // NodeX vs Node0
        const I1 = this.calculateMisinformationIndex(info.node0Answers, auditorAnswers); // Node0 vs Auditor
        const I2 = this.calculateMisinformationIndex(nodeXAnswers, auditorAnswers); // NodeX vs Auditor

        // Store the misinformation indices in an array
        const misInformationIndexArray = { I0, I1, I2 };
       
        const updatedInfo = {
            infoId: info.infoId,
            content: rewrittenContent, // Store rewritten content
            nodeXAnswers: nodeXAnswers, // Answers provided by this node
            node0Answers: info.node0Answers, // Answers from Node 0
            auditorAnswers: info.auditorAnswers, // Answers from external auditor
            questions: info.questions, // Ensure questions are passed on
            misInformationIndexArray: misInformationIndexArray, // Add the misinformation index array
            sender: this.id // Update sender to the current node
        };

        console.log(`Node ${this.id} processed`);

        return updatedInfo; // Return the updated info to be saved in the articles array
    }

    calculateMisinformationIndex(answers1, answers2) {
        if (!answers1 || !answers2) {
            console.error("One of the answer arrays is undefined. Answers1:", answers1, "Answers2:", answers2);
            throw error("One of the answer arrays is undefined. Answers1:", answers1, "Answers2:", answers2,);

            return -1; // Return a special value indicating an error in calculation
        }

        if (answers1.length !== answers2.length) {
            console.error("Answer arrays are of different lengths. Answers1 length:", answers1.length, "Answers2 length:", answers2.length);
            throw error("Answer arrays are of different lengths. Answers1 length:", answers1.length, "Answers2 length:", answers2.length);
            return -1; // Return a special value indicating an error in calculation
        }

        return answers1.reduce((sum, answer, index) => sum + Math.abs(answer - answers2[index]), 0);
    }

    async distribute(info, senderId) {
        // Use Promise.all to ensure all neighbors receive the info and process it in parallel
        const distributePromises = this.neighbors.map(async (neighborId) => {
            if (neighborId !== senderId) {
                const neighbor = Node.graph.nodes.get(neighborId); // Lookup neighbor node by ID
                if (neighbor) {
                    neighbor.receiveInfo({ ...info, sender: this.id });
                    return neighbor.processInfo(); // Neighbor starts processing in parallel
                }
            }
        });

        // Wait for all neighbors to receive and start processing in parallel
        await Promise.all(distributePromises);
    }

    receiveInfo(infoObj) {
        this.queue.push(infoObj);
    }
}

class Graph {
    constructor() {
        this.nodes = new Map(); // Store all nodes by their ID
        Node.graph = this; // Assign the current graph instance to the static property of Node class
    }

    addNode(id, prompt) {
        const node = new Node(id, prompt); // No need to pass the graph anymore
        this.nodes.set(id, node);
        return node;
    }

    addEdge(sourceId, targetId) {
        const sourceNode = this.nodes.get(sourceId);
        const targetNode = this.nodes.get(targetId);
        if (sourceNode && targetNode) {
            sourceNode.addNeighbor(targetId); // Add neighbor by ID
        }
    }

    // Send info from Node 0 with the initial article, generated questions, and auditor answers
    async sendInfo(sourceId, infoId, content, questions) {
        const sourceNode = this.nodes.get(sourceId);
        if (sourceNode) {
            if (!questions || questions.length === 0) {
                console.error("No questions generated for Node 0");
                return;
            }

            const node0Answers = await answerQuestions(content, questions,'You are an avid news reader who likes to read about news and share it with others, often in a hoax way and distorting the original facts and mostly hyping up.');

            const info = new Info(infoId, content, sourceId, questions, node0Answers); // Pass down the generated questions

            sourceNode.receiveInfo(info);
            await sourceNode.processInfo(); // Ensure Node 0 processes before sending to neighbors
        }
    }

    // Save the graph structure to a file
    saveGraphToFile(filename, neighborRanges) {
        const graphData = {
            nodes: Array.from(this.nodes.values()).map(node => ({
                id: node.id,
                prompt: node.prompt,   // The prompt used by the node
                articles: node.articles, // The articles processed by the node
                neighbors: node.neighbors // Neighbors (edges) by their ID
            })),
            edges: Array.from(this.nodes.entries()).flatMap(([sourceId, node]) =>
                node.neighbors.map(neighbor => ({ source: sourceId, target: neighbor }))
            ),
            neighborRanges: neighborRanges
        };

        try {
            fs.writeFileSync(filename, JSON.stringify(graphData, null, 4)); // Save graph to a file
            console.log(`Graph data has been saved to ${filename}`);
        } catch (error) {
            console.error(`Error writing to file: ${error.message}`);
        }
    }

    async processAllNodes(filename, neighborRanges) {
        const processPromises = Array.from(this.nodes.values()).map(node => node.processInfo());

        // Wait for all nodes to complete processing
        await Promise.all(processPromises);
        console.log("All nodes have completed processing.");

        // After all nodes have finished processing, write the graph data to the file
        this.saveGraphToFile(filename, neighborRanges);
    }
}


// Helper function to generate questions using OpenAI API, returning a JSON object
async function generateQuestions(text) {
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
            { role: "system", content: "You are an external auditor assigned to generate yes/no questions based on a given text. Your questions should be fact-based and cover various aspects of the incident, including potential developments or rumors that might arise in later versions of the story. Return your response as a JSON object with a 'questions' key containing an array of 5 strings." },
            { role: "user", content: `Generate only 5 yes/no questions based on the following text and potential developments that might occur in later versions of the story. The questions should cover various aspects such as the incident itself, the company's response, potential investigations, public concerns, and possible rumors or allegations that might arise.\n\nOriginal Article:\n${text}\n\nProvide your response as a JSON object with a 'questions' key containing an array of 5 strings.` }
        ],
        response_format: { type: "json_object" } // Specify JSON response format
    });

    const result = JSON.parse(response.choices[0].message.content);
    if (!result.questions || result.questions.length === 0) {
        throw new Error("No questions were generated.");
    }

    return result.questions;
}

// Rewrite the content using the prompt and OpenAI API, returning a JSON object with newArticle
async function rewriteContent(content, prompt) {
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
            { role: "system", content: `${prompt}` },
            { role: "user", content: `Create a new versions of this article, based on your personality.  Here's the original article:\n\n${content}\n\n Provide your response as a JSON object with a 'article' as key containing an string, as version of the article` }
        ],
        response_format: { type: "json_object" }
    });

    const result = JSON.parse(response.choices[0].message.content);
    return result.article; // The rewritten article based on the node's prompt
}

// Answer the questions using OpenAI API, returning a JSON object with answers
async function answerQuestions(content, questions, prompt) {
    if (!questions || questions.length === 0) {
        console.error("No questions provided for answering.");
        return []; // Return an empty array if no questions are provided
    }

    try {
        const response = await openai.chat.completions.create({
            model: "gpt-3.5-turbo",
            messages: [
                { role: "system", content: `${prompt}. You always return the answer array of the same length of question. You Provide your response as a JSON object with an 'answers' key containing an array of 1 (for Yes) or 0 (for No) or -5 if fact is not present in the question but` },
                { role: "user", content: `Answer the following questions:\n${questions.join('\n')} based on your personality considering the content:${content}. Provide your response as a JSON object with an 'answers' key containing an array of 1 (for Yes) or 0 (for No) or -5 if fact is not present in the question. Make sure to return same number of answer as there are questions` }
            ],
            response_format: { type: "json_object" } // Specify JSON response format
        });

        const result = JSON.parse(response.choices[0].message.content);
        if (!result.answers || result.answers.length === 0) {
            throw new Error("No valid answers received from OpenAI.");
        }

        return result.answers; // Return the answers in an array of 1 (Yes) or 0 (No)

    } catch (error) {
        console.error("Error while calling OpenAI API for answering questions:", error);
        return []; // Return an empty array if there's an error
    }
}

const content = `A human finger was discovered in a tub of ice cream purchased from a local grocery store in Springfield.
The shocking find was made by a customer who immediately reported it to the authorities. Springfield
Police Department has launched an investigation to determine how the finger ended up in the ice cream.

Preliminary findings suggest that the incident might be linked to an industrial accident at the manufac-
turing plant. Thaloria Ice Cream, the brand involved, has issued a public apology and is cooperating

fully with the investigation. The company has also initiated a recall of the affected batch as a precau-
tionary measure. Health officials have assured the public that there is no immediate health risk. This

incident has sparked discussions about food safety standards and the importance of stringent quality
control measures in food production.`;

// Example Graph Creation and Execution
// (async () => {
//     const graph = new Graph();

//     // Total number of agents
//     const numAgents = agents.length; // 21 agents in total
//     const nodesPerAgent = 30; // Number of nodes per agent type
//     const totalNodes = numAgents * nodesPerAgent; // Total number of nodes

//     // Add Node 0 with its specific prompt
//     graph.addNode(0, 'You are an avid news reader who likes to read about news and share it with others, often in a hoax way and distorting the original facts and mostly hyping up.');

//     // Create nodes from 1 to totalNodes using agents
//     for (let i = 1; i <= totalNodes; i++) {
//         const agentIndex = Math.floor((i - 1) / nodesPerAgent); // Assign agent type based on the range
//         graph.addNode(i, agents[agentIndex].prompt); // Use agent's prompt based on index
//     }

//     // Programmatically define the edges in the same pattern as your edgesGraph1 structure
//     const interval = 30; // Interval to connect nodes from the main node
//     const branchLength = 30; // Number of sequential nodes connected from each interval node

//     for (let i = 1; i <= totalNodes; i += interval) {
//         // Connect the main node (0) to the first node of each branch (e.g., 1, 16, 31, ...)
//         graph.addEdge(0, i);

//         // Connect nodes within each branch sequentially
//         for (let j = i; j < i + branchLength - 1 && j < totalNodes; j++) {
//             graph.addEdge(j, j + 1); // Sequentially connect nodes within the branch
//         }

//         // No connection between the last node of one branch and the first node of the next branch
//         // This ensures node 15 doesn't connect to 16, node 30 doesn't connect to 31, etc.
//     }

//     // Generate questions based on the news article
//     const questions = await generateQuestions(content);

//     // Generate external auditor answers based on the article and questions
//     //const auditorAnswers = await answerQuestions(content, questions, "You are an external fact checker that answers yes/no questions based on a given text. Return your response as a JSON object with an 'answers' key containing an array of 1 (for Yes) or 0 (for No).");

//     // Send the news to a random node (excluding Node 0) for processing
//     //await graph.sendInfo(0, `info-${'category'}-0${'i'}`, content, questions, auditorAnswers, `You are an avid news reader who likes to read about news and share it with others, often in a hoax way and distorting the original facts and mostly hyping up.`); // Use the agent's prompt for the node
//     await graph.sendInfo(0, `info-${'category'}-0${'i'}`, content, questions)

//     // Process all nodes in the graph
//     await graph.processAllNodes();

//     // Save the graph's output to a file or perform further operations
// })();

// (async () => {
//     const graph = new Graph();

//     // Total number of agents
//     const numAgents = agents.length; // 21 agents in total
//     const nodesPerAgent = 30; // Number of nodes per agent type
//     const totalNodes = numAgents * nodesPerAgent; // Total number of nodes

//     // Add Node 0 with its specific prompt
//     graph.addNode(0, 'You are an avid news reader who likes to read about news and share it with others, often in a hoax way and distorting the original facts and mostly hyping up.');

//     // Create nodes from 1 to totalNodes using agents
//     for (let i = 1; i <= totalNodes; i++) {
//         const agentIndex = Math.floor((i - 1) / nodesPerAgent); // Assign agent type based on the range
//         graph.addNode(i, agents[agentIndex].prompt); // Use agent's prompt based on index
//     }

//     // Connect nodes programmatically
//     const interval = 30;
//     for (let i = 1; i <= totalNodes; i += interval) {
//         graph.addEdge(0, i);
//         for (let j = i; j < i + interval - 1 && j < totalNodes; j++) {
//             graph.addEdge(j, j + 1); // Sequentially connect nodes within the branch
//         }
//     }

//     // Example content
//     const content = "Sample news article content";
//     const questions = await generateQuestions(content);

//     // Send the news to Node 0 for processing
//     await graph.sendInfo(0, `info-category-01`, content, questions);

//     // Process all nodes
//     await graph.processAllNodes();
// })();

(async () => {
    const graph = new Graph();

    // Total number of agents
    const numAgents = agents.length; // 21 agents in total
    const nodesPerAgent = 4; // Number of nodes per agent type
    const totalNodes = numAgents * nodesPerAgent; // Total number of nodes

    // Array to store ranges of each neighbor of Node 0
    const neighborRanges = [];

    // Add Node 0 with its specific prompt
    graph.addNode(0, 'You are an avid news reader who likes to read about news and share it with others, often in a hoax way and distorting the original facts and mostly hyping up.');

    // Create nodes from 1 to totalNodes using agents
    for (let i = 1; i <= totalNodes; i++) {
        const agentIndex = Math.floor((i - 1) / nodesPerAgent); // Assign agent type based on the range
        graph.addNode(i, agents[agentIndex].prompt); // Use agent's prompt based on index
    }

    // Connect nodes programmatically
    //const interval = nodesPerAgent;
    for (let i = 1; i <= totalNodes; i += nodesPerAgent) {
        // Connect Node 0 to the first node in the current branch
        graph.addEdge(0, i);

        // Store the range of nodes connected to this neighbor of Node 0
        neighborRanges.push([i, Math.min(i + nodesPerAgent - 1, totalNodes)]);

        // Connect nodes within each branch sequentially
        for (let j = i; j < i + nodesPerAgent - 1 && j < totalNodes; j++) {
            graph.addEdge(j, j + 1); // Sequentially connect nodes within the branch
        }
    }

//    console.log("neighborRanges:", neighborRanges)

   // const content = "Sample news article content";
    const questions = await generateQuestions(content);

    // Send the news to Node 0 for processing
    await graph.sendInfo(0, `info-category-01`, content, questions);

    // Process all nodes and pass neighborRanges to processAllNodes
    await graph.processAllNodes('testss.json', neighborRanges);
})();

